# Generated by Django 3.1.5 on 2021-03-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_liked',
            new_name='user_like',
        ),
    ]
